# Generated by Django 5.0.2 on 2024-03-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='name',
            field=models.CharField(default='unnamed subject', max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='video_link',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
